//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop {
    
    
    public partial class CustomerHomepage {
        
        /// <summary>
        /// CustomerCategoriesList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EShop.UserControls.CustomerCategoriesList CustomerCategoriesList;
        
        /// <summary>
        /// CustomerSearchBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EShop.UserControls.CustomerSearchBox CustomerSearchBox;
        
        /// <summary>
        /// CustomerHomepage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EShop.UserControls.CustomerHomepage CustomerHomepage1;
    }
}
